home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('orders.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('feedback/', include('feedback.urls')),
    path('about/', include('about.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profile, name='profile'),
    path('order_history/<order_number>', views.order_history,
         name='order_history'),
    path('turtle_history', views.turtle_history, name='turtle_history'),
]

orders/models.py
import uuid
import datetime
from datetime import timedelta
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.db.models import Sum
from django_countries.fields import CountryField

from profiles.models import UserProfile

SPECIES = [
        ('logger', 'Loggerhead'),
        ('green', 'Green'),
        ('leather', 'Leatherback'),
        ('flat', 'Flatback'),
        ('hawks', 'Hawksbill'),
        ('olive', 'Olive Ridley'),
        ("kemp", "Kemp's Ridley"),
    ]


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Categories'
    # programmatic name
    name = models.CharField(max_length=254)
    # front end name
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    sku = models.CharField(max_length=254, null=False, blank=False)
    title = models.CharField(max_length=254, null=False, blank=False)
    price = models.DecimalField(max_digits=6, decimal_places=2, null=False,
                                blank=False)
    description = models.TextField(null=False, blank=False)
    rating = models.DecimalField(max_digits=6, decimal_places=2, null=True,
                                 blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("view_product", kwargs={
            'slug': self.slug
        })

    def get_add_to_basket_url(self):
        return reverse("add_to_basket", kwargs={
            'slug': self.slug
        })

    def get_remove_from_basket_url(self):
        return reverse("remove_from_basket", kwargs={
            'slug': self.slug
        })


class Order(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    order_number = models.CharField(max_length=32, null=False, editable=False)
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Choose country *', null=False,
                           blank=False, max_length=100)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2,
                                        null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    # text field that will contain the original shopping bag that created it
    original_basket = models.TextField(null=False, blank=False, default='')
    # character field that will contain the unique stripe payment intent id
    stripe_pid = models.CharField(max_length=254, null=False, blank=False,
                                  default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        This generated a string of 32 numbers
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        self.order_total = self.orderitems.aggregate(
                           Sum('orderitem_total'))['orderitem_total__sum'] or 0
        self.delivery_cost = self.order_total * settings. \
            STANDARD_DELIVERY_PERCENTAGE / 100
        self.grand_total = self.order_total + self.delivery_cost
        self.save()
        # return self.grand_total

    # override default save method
    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            # If the current order doesn't have an order number, one is
            # assigned
            self.order_number = self._generate_order_number()
        # then execute original save method
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderItem(models.Model):
    order = models.ForeignKey(Order, null=True, blank=True,
                              on_delete=models.CASCADE,
                              related_name='orderitems')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)
    orderitem_total = models.DecimalField(max_digits=6, decimal_places=2,
                                          null=True, blank=True,
                                          editable=False)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

    def save(self, *args, **kwargs):
        self.orderitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

# code credit
# https://stackoverflow.com/questions/2199013/how-can-my-django-model-
# datefield-add-30-days-to-the-provided-value/2199371
def get_sponsorship_end():
    return datetime.date.today() + timedelta(days=365)


class Turtles(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE,
                                   related_name='turtle', null=True)
    sponsored_status = models.BooleanField(default=False, null=False,
                                           blank=False)
    species = models.CharField(choices=SPECIES, max_length=10, null=False,
                               blank=False)
    name = models.CharField(max_length=50)
    sponsorship_start = models.DateField(auto_now_add=True)
    sponsorship_end = models.DateField(default=get_sponsorship_end)
    turtle_id = models.CharField(max_length=10, unique=True, null=True,
                                 blank=True)
    tagged_in = CountryField(blank_label='Choose country', max_length=100)
    current_location = models.ImageField(null=True, blank=True)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from django_countries.fields import CountryField


class UserProfile(models.Model):
    """
    A user profile model for maintaining default
    delivery information and order history
    """
    # one to one specifies each user can only have one profile and vice versa
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # info grabbed from order model - made default and optional
    default_full_name = models.CharField(max_length=50, null=True, blank=True)
    default_email = models.EmailField(max_length=200, null=True, blank=True)
    default_phone_number = models.CharField(max_length=20, null=True,
                                            blank=True)
    default_street_address1 = models.CharField(max_length=80, null=True,
                                               blank=True)
    default_street_address2 = models.CharField(max_length=80, null=True,
                                               blank=True)
    default_town_or_city = models.CharField(max_length=40, null=True,
                                            blank=True)
    default_postcode = models.CharField(max_length=20, null=True, blank=True)
    default_country = CountryField(blank_label='Country', null=True,
                                   blank=True)

    def __str__(self):
        return self.user.username


# This is here so that each time a user object is saved. We'll automatically
# either create a profile for them if the user has just been created, or just
# save the profile to update it if the user already existed.
@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    """
    Create or update the user profile
    """
    if created:
        UserProfile.objects.create(user=instance)
    # Existing users: just save the profile
    instance.userprofile.save()

profiles/forms.py
from django import forms
from orders.models import Turtles
from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            # add default to the front to match model
            'default_full_name': 'Full Name',
            'default_email': 'Email',
            'default_phone_number': 'Phone Number',
            'default_postcode': 'Postal Code',
            'default_town_or_city': 'Town or City',
            'default_street_address1': 'Street Address 1',
            'default_street_address2': 'Street Address 2',
        }

        self.fields['default_full_name'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if field != 'default_country':
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'border-black rounded-0 \
                profile-form-input'
            self.fields[field].label = False

profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from orders.models import Order
from .models import UserProfile
from .forms import UserProfileForm


def order_history(request, order_number):
    # get the order
    order = get_object_or_404(Order, order_number=order_number)

    # Add message to tell user they're looking at a past order confirmation
    messages.info(request, (
        f'This is a past confirmation for order number {order_number}. '
        'A confirmation email was sent on the order date.'
    ))

    template = 'checkout/checkout_success.html'
    context = {
        'order': order,
        # add the variable from_profile to check in that template if the user
        # got there via the order history view
        'from_profile': True,
    }

    return render(request, template, context)


@login_required
def profile(request):
    """ Display the user's profile. """
    profile = get_object_or_404(UserProfile, user=request.user)

    if request.method == 'POST':
        # Create a new instance of the user profile form using the post data
        # and tell it the instance we're updating is the profile we've just
        # retrieved above.
        form = UserProfileForm(request.POST, instance=profile)
        # Then if the form is valid, save it and add a success message.
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request,
                           'Update failed. Please ensure the form is valid.')
    else:
        form = UserProfileForm(instance=profile)
    orders = profile.orders.all()

    template = 'profiles/profile.html'
    context = {
        'form': form,
        'orders': orders,
        'on_profile_page': True
    }

    return render(request, template, context)


def turtle_history(request):
    """ Display the user's profile. """
    profile = get_object_or_404(UserProfile, user=request.user)
    orders = profile.orders.all()

    template = 'profiles/turtle_sponsorship.html'
    context = {
        'orders': orders,
        'on_profile_page': True
    }

    return render(request, template, context)

profiles/templates/profiles/profile.html
{% extends "base.html" %}
{% load static %}

{% comment %} This js which allows to submit forms through ajax and must be loaded in the page{% endcomment %}
{% block extra_js%}
    <script src="http://malsup.github.com/jquery.form.js"></script>
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'profiles/css/profile.css' %}">
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col">
            <hr>
            <h2 class="logo-font mb-4"> {{ user.username }}'s Profile</h2>
            <hr>
        </div>
    </div>

    <div class="row">

        <!-- default delivery info  -->

        <div class="col-12 col-lg-6">
            <p class="text-muted">Default Delivery Information</p>
            <form class="mt-3" action="{% url 'profile' %}" method="POST" id="profile-update-form">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-black rounded-0 text-uppercase float-right">Update Information</button>
            </form>
        </div>

        <!-- order history -->

        <div class="col-12 col-lg-6">
            <p class="text-muted">Order History</p>
            <!-- create a small bootstrap table  -->
            <div class="order-history table-responsive">
                <table class="table table-sm table-borderless">
                    <thead>
                        <tr>
                            <th>Order Number</th>
                            <th>Date</th>
                            <th>Order Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                        <tr>
                            <td>
                                <!-- disply 6 numbers only, but show full with hover  -->
                                <a href="{% url 'order_history' order.order_number %}" title="{{ order.order_number }}">
                                    {{ order.order_number|truncatechars:6 }}
                                </a>
                            </td>
                            <td>{{ order.date }}</td>
                            <td>
                                <!-- unordered, unstyled list  -->
                                <ul class="list-unstyled">
                                    <!-- For each item in the orders list of line-items  -->
                                    {% for item in order.orderitems.all %}
                                    <li class="small">
                                        <!-- product name and quantity  -->
                                        {{ item.product.title }} x{{ item.quantity }}
                                    </li>
                                    {% endfor %}
                                </ul>
                            </td>
                            <td>€{{ order.grand_total }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <h2> Turtle Information</h2>
    <p>If you have sponsored any turtles you will find their info below</p>
    <div class="row">
        <div class="col-12">
            {% if orders %}
                {% for order in orders %}
                    {% for item in order.orderitems.all %}
                        {% if item.product.category.name == 'turtles' %}
                            YOU SPONSORED TURTLES<br>
                            <a href="{% url 'order_history' order.order_number %}" title="{{ order.order_number }}">Order number:
                                {{ order.order_number }}</a><br>
                            Order date: {{ order.date }}<br>
                            Order title: {{ item.product.title }}<br>
                            Name: {{ item.product.turtle.name }}<br>
                            ID: {{item.product.turtle.turtle_id }}<br>
                            Species: {{ item.product.turtle.get_species_display }}<br>
                            Country tagged: {{item.product.turtle.tagged_in }}<br>
                            Sponsorship start date: {{ item.product.turtle.sponsorship_start }}<br>
                            Sponsorship end date: {{ item.product.turtle.sponsorship_end }}<br>
                            Picture of {{  item.product.turtle.name }}: {{ item.product.image }}<br>
                            Current location: {{item.product.turtle.current_location}}<br><br>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script type="text/javascript" src="{% static 'profiles/js/countryfield.js' %}"></script>
{% endblock %}

profiles/templates/profiles/turtle_sponsorship.html
{% extends "base.html" %}
{% load static %}

{% comment %} This js which allows to submit forms through ajax and must be loaded in the page{% endcomment %}
{% block extra_js%}
    <script src="http://malsup.github.com/jquery.form.js"></script>
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'profiles/css/profile.css' %}">
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col">
            <hr>
            <h2 class="logo-font mb-4"> {{ user.username }}'s Sponsored Turtles</h2>
            <hr>
        </div>
    </div>

    <h2> Turtle Information</h2>
    <p>If you have sponsored any turtles you will find their info below</p>
    <p>To name your turtle please send us a message using <a href="{% url 'contact' %}">this</a> contact form with the subject "NAME MY TURTLE" and mention your turtle's ID</p>
    <div class="row">
        <div class="col-12">
            {% if orders %}
                {% for order in orders %}
                    {% for item in order.orderitems.all %}
                        {% if item.product.category.name == 'turtles' %}
                            YOU SPONSORED TURTLES<br>
                            <a href="{% url 'order_history' order.order_number %}" title="{{ order.order_number }}">Order number:
                                {{ order.order_number }}</a><br>
                            Order date: {{ order.date }}<br>
                            Order title: {{ item.product.title }}<br>
                            Name: {{ item.product.turtle.name }}<br>
                            ID: {{item.product.turtle.turtle_id }}<br>
                            Species: {{ item.product.turtle.get_species_display }}<br>
                            Country tagged: {{item.product.turtle.tagged_in }}<br>
                            Sponsorship start date: {{ item.product.turtle.sponsorship_start }}<br>
                            Sponsorship end date: {{ item.product.turtle.sponsorship_end }}<br>
                            Picture of {{  item.product.turtle.name }}: {{ item.product.image }}<br>
                            Current location: {{item.product.turtle.current_location}}<br><br>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script type="text/javascript" src="{% static 'profiles/js/countryfield.js' %}"></script>
{% endblock %}