feedback/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.TestimonialView.as_view(), name='testimonials'),
    path('add_testimonial/', views.CreateTestimonial.as_view(),
         name='add_testimonial'),
    path('edit/<testimonial_id>', views.edit_testimonial,
         name='edit_testimonial'),
    path('delete/<testimonial_id>', views.delete_testimonial,
         name='delete_testimonial'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('orders.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('feedback/', include('feedback.urls')),
    path('about/', include('about.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator


# Help with min and max
# https://stackoverflow.com/questions/849142/how-to-limit-the-maximum-value-of-
# a-numeric-field-in-a-django-model
class Testimonials(models.Model):
    reviewed_by = models.ForeignKey(User, on_delete=models.CASCADE,
                                    related_name="reviews")
    reviewed_on = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(validators=[MinValueValidator(1),
                                             MaxValueValidator(5)])
    content = models.TextField(max_length=500)
    icon = models.ImageField(null=True, blank=True)

    class Meta:
        ordering = ['reviewed_on']

    def __str__(self):
        return f"{self.reviewed_by.username} gave a rating of {self.rating}"

feedback/forms.py
from django import forms
from .models import Testimonials


class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonials
        exclude = ['reviewed_by']

feedback/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.views import generic
from django.contrib import messages
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Testimonials
from .forms import TestimonialForm


class TestimonialView(generic.ListView):
    model = Testimonials
    template_name = 'feedback/testimonials.html'


class CreateTestimonial(LoginRequiredMixin, CreateView):
    model = Testimonials
    form_class = TestimonialForm
    template_name = 'feedback/add_testimonial.html'
    success_message = "Thank you for your feedback :)"

    def get_success_url(self):
        return reverse('testimonials')

    def form_valid(self, form):
        form.instance.reviewed_by = self.request.user
        print(form.cleaned_data)
        return super().form_valid(form)


class EditTestimonial(LoginRequiredMixin, UpdateView):
    model = Testimonials
    form_class = TestimonialForm
    template_name = 'feedback/edit_testimonial.html'

    def get_object(self, queryset=None):
        return Testimonials.objects.get(pk=self.request.GET.get('pk'))


@login_required
def edit_testimonial(request, testimonial_id):
    """ Edit a product in the store """

    test = get_object_or_404(Testimonials, pk=testimonial_id)

    if test.reviewed_by != request.user or not request.user.is_superuser:
        messages.error(request, 'Sorry, you do not have permission to do that')
        return redirect(reverse('testimonials'))

    # post handler
    if request.method == 'POST':
        # instantiate a form using request.post and request.files using the
        # instance of the product gotten above
        form = TestimonialForm(request.POST, request.FILES, instance=test)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated your testimonial!')
            return redirect(reverse('testimonials'))
        else:
            messages.error(request, 'Failed to update product. Please ensure \
                the form is valid.')
    else:
        # display prefilled form
        form = TestimonialForm(instance=test)
        messages.info(request, 'You are editing your testimonial')

    template = 'feedback/edit_testimonial.html'
    context = {
        'form': form,
        'test': test,
    }

    return render(request, template, context)


@login_required
def delete_testimonial(request, testimonial_id):

    test = get_object_or_404(Testimonials, pk=testimonial_id)

    if test.reviewed_by != request.user or not request.user.is_superuser:
        messages.error(request, 'Sorry, you do not have permission to do that')
        return redirect(reverse('testimonials'))

    test.delete()
    messages.success(request, 'Deleted that testimonial')
    return redirect(reverse('testimonials'))

feedback/templates/feedback/add_testimonial.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">

        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>

<h1>Customer Testimonials</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-3 left">
           
        </div>
    </div>
</div>

<form method="POST" enctype="multipart/form-data">

    <!-- Security token -->
    {% csrf_token %}
    <div class="container recipe-form">
        <div class="card">
            <div class="card-body">
                {% crispy form %}
            </div>
        </div>
        <button class="form-submit box-button" type="submit">Submit</button>
    </div>

</form>

{% endblock %}

feedback/templates/feedback/edit_testimonial.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">

        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>

<h1>Customer Testimonials</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-3 left">
           
        </div>
    </div>
</div>

<form method="POST" enctype="multipart/form-data">

    <!-- Security token -->
    {% csrf_token %}
    <div class="container recipe-form">
        <div class="card">
            <div class="card-body">
                {% crispy form %}
            </div>
        </div>
        <button class="form-submit box-button" type="submit">Submit</button>
    </div>

</form>

{% endblock %}

feedback/templates/feedback/testimonials.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">

        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>

<div class="container">
    <hr>
    <h1>Customer Testimonials</h1>
    <hr>

    <p class="text-center"><i class="fas fa-dragon"></i></p>
    <p>
        <p class="text-center">A note to all users:</p><br>
        This dragon is our feedback guardian. We like to be 100% honest and open with our
        audience which is why this review section is free to be added to by all registered users. We want this to be a
        safe space for all users to voice their experience. If you leave us a negative (but valid) review we will not
        remove it, but will endeavour to rectify any mistakes we have made.<br> HOWEVER, absolutely no profanity,
        vulgarity or abusive language will be tolerated. Your
        testimonial will be removed <strong>immediately</strong> if it is deemed inappropriate and your account will be
        removed. We're all about second chances, but our dragon guardian finds this behaviour inexcusable and there will
        be no
        second chance for you. <br> All our love, the Ridley Me This team x
    </p>
    {% if user.is_authenticated %}
    <a href="{% url 'add_testimonial' %}" class="btn btn-success">Add a testimonial</a>
    {% endif %}
    <br>
    <br>
    {% for testimonial in testimonials_list %}
    <div class="row">
        <!-- <div class="row"> -->
        <!-- <div class="row"> -->
        <div class="col-12">
            {% if testimonial.icon %}
            <img class="icon" src="{{ testimonial.icon.url }}" alt="User's uploaded image">
            {% else %}
            <img class="icon" src="{{ MEDIA_URL }}icon.png" alt="default turtle icon">
            {% endif %}
            <strong>{{ testimonial.reviewed_by }}</strong> says:
        </div>
        <br>
        <div class="col offset-1">
            <strong>Rating:{{ testimonial.rating }}/5 </strong><br>
            {{ testimonial.content }}<br>
            <span class="small">{{ testimonial.reviewed_on}}</span>
            {% if user.is_superuser %}
            <a href="{% url 'delete_testimonial' testimonial.id %}" class="small">delete</a>
            {% elif user.is_authenticated and user == testimonial.reviewed_by %}
            <a href="{% url 'edit_testimonial' testimonial.id %}" class="small">edit</a>
            <a href="{% url 'delete_testimonial' testimonial.id %}" class="small">delete</a>
            {% endif %}
        </div>
        <br>
    </div>
    <br>
    {% endfor %}

</div>


<!-- pagination -->
{% if is_paginated %}
<div class="pagination">
    <div class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; First</a>
        <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </div>
</div>
{% endif %}

{% endblock %}